### ISSUE TITLE
ClassCastException in getPriorityMap() function Tower != List

### ISSUE THREAD

**Issue by BetmanSmall** [BetmanSmall/TowerDefence_GDX#12]
Steps:
1. Run Desktop Application
2. Open GameScreen
3. Build a lot of towers
4. Get ClassCastException

It took me about 423 towers

![image](https://cloud.githubusercontent.com/assets/5994526/16933181/2f3093e2-4d54-11e6-98b8-631957fcfeed.png)
![image](https://cloud.githubusercontent.com/assets/5994526/16933194/3fc8b2e8-4d54-11e6-9e09-c2afa6a6f05d.png)

**Comment by Transet** [comment]
looks like the multithreading problem.
