### ISSUE TITLE
Отрисовка карты

### ISSUE THREAD

**Issue by BetmanSmall** [BetmanSmall/TowerDefence_GDX#16]
Отрисовать эту ёбанную карту в правильном порядке. А правильный порядок, я блять хуй его знает какой...
Надо сделать так, что бы криппы и текстурки перекрывали друг друга там где нужно, и не перекрывали там где не нужно.....
![](http://lurkmore.so/images/a/af/FFUUUUUU.png)

**Comment by BetmanSmall** [comment]
x=min, y=max;
x=min, y=max-1;
x=min+1, y=max;
x=min, y=max-2;
x=min+1, y=max-1;
x=min-2, y=max;
x=min, y=max-3;
x=min+1, y=max-2;
x=min+2, y=max-1;
x=min+3, y=max;
x=min, y=max-4;
x=min+1, y=max-3;
x=min+2, y=max-2;
x=min+3, y=max-1;
x=min+4, y=max;
x=min, y=max-5;
x=min+1, y=max-4;
x=min+2, y=max-3;
x=min+3, y=max-2;
x=min+4, y=max-1;
x=min+5, y=max;
x=min, y=max-6;
x=min+1, y=max-5;
x=min+2, y=max-4;
x=min+3, y=max-3;
x=min+4, y=max-2;
x=min+5, y=max-1;
x=min+6, y=max;
x=min, y=max-7;
x=min+1, y=max-6;
x=min+2, y=max-5;
x=min+3, y=max-4;
x=min+4, y=max-3;
x=min+5, y=max-2;
x=min+6, y=max-1;
x=min+7, y=max;
x=min, y=max-8;

**Comment by zloeby4i** [comment]
x=0, y=0;
x=0, y=1;
x=1, y=0;
x=0, y=2;
x=1, y=1;
x=2, y=0;
x=0, y=3;
x=1, y=2;
x=2, y=1;
x=3, y=0;
x=0, y=4;
x=1, y=3;
x=2, y=2;
x=3, y=1;
x=4, y=0;
x=0, y=5;
x=1, y=4;
x=2, y=3;
x=3, y=2;
x=4, y=1;
x=5, y=0;
x=0, y=6;
x=1, y=5;
x=2, y=4;
x=3, y=3;
x=4, y=2;
x=5, y=1;
x=6, y=0;
x=0, y=7;
x=1, y=6;
x=2, y=5;
x=3, y=4;
x=4, y=3;
x=5, y=2;
x=6, y=1;
x=7, y=0;
x=0, y=8;

**Comment by BetmanSmall** [comment]
Closed #fc94714
