### ISSUE TITLE
Lags during setting a tower.

### ISSUE THREAD

**Issue by Transet** [BetmanSmall/TowerDefence_GDX#3]
I have a big problem on my device. I think, It would be better to provide a parallel work for algorithm or provide several rules that can significantly decrease the load.

**Comment by BetmanSmall** [comment]
А кто у нас лучше всех знает много поточность?

**Comment by Transet** [comment]
I can take it, but I have not time for this. This is a good possibility to increase your acknowledgment in this area : )
May be we can assign this user story to Andrey. What do you think about it?
