### ISSUE TITLE
The screen of settings.

### ISSUE THREAD

**Issue by Transet** [BetmanSmall/TowerDefence_GDX#5]
I opened this issue in order to track the progress on the creating the screen of settings. Feel free to discuss of what exactly we want to see on this screen.

**Comment by Transet** [comment]
Probably bug?

**Comment by Transet** [comment]
Sorry about it. Keep tracking.

**Comment by BetmanSmall** [comment]
Дим. Давай по русски! Мы кто? Русские. Так что давай спрехать по раша.

**Comment by Transet** [comment]
> Так что давай спрехать по раша.

В рамках открытого исходного кода, я считаю что лучше использовать английский язык. Но пока можно и русским обойтись.

**Comment by Transet** [comment]
Предлагаю назначить дьюдейт как 28 марта.
